# Site settings
author: Skyler Littleaxe
title: Late Night Coding
header-img: img/home-bg.png
email: littleaxe.skyler@gmail.com
copyright_name: Skyler Littleaxe
description: > # this means to ignore newlines until "baseurl:"
  My journey to becoming an software engineer. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  skyler-littleaxe

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
